USE [GD1C2021]
GO

--SE CREA EL ESQUEMA

if(not exists(select * from INFORMATION_SCHEMA.SCHEMATA where SCHEMA_NAME = 'GESTION_DE_GATOS'))
  begin
      exec ('CREATE SCHEMA[GESTION_DE_GATOS] AUTHORIZATION [GD1C2021]');
      print 'esquema creado';
    end


--CREAR TABLAS BASE DE DATOS

--SUCURSAL
IF OBJECT_ID ('GESTION_DE_GATOS.SUCURSAL', 'U') IS NOT NULL  
   DROP TABLE GESTION_DE_GATOS.SUCURSAL; 
GO
CREATE TABLE GESTION_DE_GATOS.SUCURSAL (
SUCURSAL_MAIL NVARCHAR(255),
SUCURSAL_DIRECCION NVARCHAR(255) NOT NULL,
SUCURSAL_CIUDAD NVARCHAR(255) NOT NULL,
SUCURSAL_TELEFONO DECIMAL(18,0) NOT NULL,
PRIMARY KEY(SUCURSAL_MAIL)
);

--CLIENTE
IF OBJECT_ID ('GESTION_DE_GATOS.CLIENTE', 'U') IS NOT NULL  
   DROP TABLE GESTION_DE_GATOS.CLIENTE; 
GO
CREATE TABLE GESTION_DE_GATOS.CLIENTE (
CLIENTE_MAIL NVARCHAR(255) NOT NULL,
CLIENTE_DNI DECIMAL(18,0) NOT NULL,
CLIENTE_APELLIDO NVARCHAR(255) NOT NULL,
CLIENTE_FECHA_NAC DATETIME2(3) NOT NULL,
CLIENTE_TELEFONO INT NOT NULL,
CLIENTE_DIRECCION NVARCHAR(255) NOT NULL,
PRIMARY KEY(CLIENTE_MAIL)
);


--MIGRACION SUCURSAL
IF OBJECT_ID ('GESTION_DE_GATOS.migracionSucursal', 'P') IS NOT NULL  
   DROP PROCEDURE GESTION_DE_GATOS.migracionSucursal; 
GO
CREATE PROCEDURE GESTION_DE_GATOS.migracionSucursal AS
BEGIN
	INSERT INTO GESTION_DE_GATOS.SUCURSAL
		SELECT DISTINCT SUCURSAL_MAIL, SUCURSAL_DIR, CIUDAD, SUCURSAL_TEL 
		FROM gd_esquema.Maestra
		WHERE SUCURSAL_MAIL IS NOT NULL
		ORDER BY SUCURSAL_MAIL
END;
GO

--MIGRACION CLIENTE
IF OBJECT_ID ('GESTION_DE_GATOS.migracionCliente', 'P') IS NOT NULL  
   DROP PROCEDURE GESTION_DE_GATOS.migracionCliente;
GO
CREATE PROCEDURE GESTION_DE_GATOS.migracionCliente AS
BEGIN
	INSERT INTO GESTION_DE_GATOS.CLIENTE
		SELECT DISTINCT CLIENTE_MAIL, CLIENTE_DNI, CLIENTE_APELLIDO,
						CLIENTE_FECHA_NACIMIENTO, CLIENTE_TELEFONO, CLIENTE_DIRECCION
		FROM gd_esquema.Maestra 
		WHERE CLIENTE_DNI IS NOT NULL --VERIFICAR
		ORDER BY CLIENTE_APELLIDO
END;
GO


--MIGRAR TODA LA BASE DE DATOS
IF OBJECT_ID ('GESTION_DE_GATOS.migrarBaseDeDatos', 'P') IS NOT NULL  
   DROP PROCEDURE GESTION_DE_GATOS.migrarBaseDeDatos; 
GO
CREATE PROCEDURE GESTION_DE_GATOS.migrarBaseDeDatos AS
BEGIN
	EXEC GESTION_DE_GATOS.migracionCliente
	EXEC GESTION_DE_GATOS.migracionSucursal
END;
GO

exec GESTION_DE_GATOS.migrarBaseDeDatos


--DEFINICION DE FKs (Pongo uno como referencia hasta que definamos bien el DER)
--FK tabla VUELO 
--ALTER TABLE NOMBRE_ESQUEMA.VUELO
--ADD CONSTRAINT FK_VUELO
--FOREIGN KEY (AVION_IDENTIFICADOR) REFERENCES NOMBRE_ESQUEMA.AVION,
--FOREIGN KEY (RUTA_AEREA_ID) REFERENCES NOMBRE_ESQUEMA.RUTA_AEREA,
--FOREIGN KEY (AEROLINEA_CODIGO) REFERENCES NOMBRE_ESQUEMA.AEROLINEA;

